### PR TITLE
Fix vararg generation & Update bindings

### LINKED ISSUE #1: ... functions expecting arrays
Functions like ``print`` are generated as so right now:
```ts
declare function print(args: any[]): void;
```

They *should* be like this instead (as far as I know)
Works for me when I manually changed it.
```ts
declare function print(...args: any[]): void;
```

~~Nice project dude, I was thinking of making this but then was pointed to this after they found it when I somehow couldn't..~~

Another Note: I think you're supposed to make all of these functions ``@noSelf`` because they're all passing nil as the first argument. https://typescripttolua.github.io/docs/the-self-parameter/

### PR DESCRIPTION
**Pull request by vurvdev**
Fixes #1
Also maybe we should make a workflow to generate the bindings to a different branch so we don't need to update it manually / it doesn't count as source code? I don't really know how npm packages handle autogenerated stuff so.

### CODE REVIEW

File: src/transformer/function.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ function transformArgs(func: WikiFunction): TSArgument[] {
         }
 
         return {
-            identifier: transformIdentifier(arg.name),
+            identifier: transformIdentifier(arg.name, type),
```
Comment (lolleko) [inline src/transformer/function.ts]: Could you move the logic you added to transformidentifier to here instead? Since this is the only place where the identifier needs to be modified this way.

Something like this:
```suggestion
            identifier: (type == "vararg" ? "..." : "") + transformIdentifier(arg.name),
```

Maybe move this to separate variable as well to improve readability.

File: package-lock.json [hunk 2]
```diff
@@ -1,133 +1,8 @@
 {
     "name": "gmod-typescript",
     "version": "1.0.0",
-    "lockfileVersion": 2,
```
Comment (lolleko) [inline package-lock.json]: Please update your npm/node version and rerun npm install. That way, the lock file version won't get downgraded.

**Review by lolleko — CHANGES_REQUESTED** [review]
Thanks for the pull request! Really appreciate the help!
I added some small remarks.
Also the declarations still require a `@noselfInFile` to fix #1.
Just add it in https://github.com/lolleko/gmod-typescript/blob/master/src/index.ts#L74 for now.
And you are right, the declarations should not be distributed via the repo.
I will publish a npm package containing these declarations once this PR is merged.

**Comment by vurvdev** [comment]
Alright, hopefully everything is fine now

**Comment by lolleko** [comment]
Thanks!
